### ISSUE TITLE
Cubes doesn't have their Annotations

### ISSUE THREAD

**Issue by frabarz** [Datawheel/mondrian-rest-client#5] opened 2018-02-20 17:50 UTC
On initialization, cubes doesn't save the info from annotations.

[This is the only reference](https://github.com/Datawheel/mondrian-rest-client/blob/master/src/cube.ts#L25) to annotations, and doesn't do anything because of the `this.`.

**Comment by jazzido** [comment] 2018-02-20 18:13
Good catch, and thanks for finding the cause.

I've just pushed a fix.

**Closed** 2018-02-20 18:13 UTC
